title: <p align="center">Shruti Misra</p> # your name (or website title) here
logo: "/images/prof_pic2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p align="center">
  <a href="https://www.linkedin.com/in/shrutim14/">LinkedIn</a> |
  <a href="https://github.com/shruti-misra">GitHub</a> | 
  <a href="https://shruti-misra.github.io/">Website</a>
  </p>
  <p align="justify">
 With a background in data science and computer engineering, I bring extensive experience in handling diverse datasets and using advanced statistical and machine learning methods. I also enjoy storytelling by designing interactive data visualizations (often in Python or Tableau), to effectively communicate data-driven narratives to diverse audiences.
  <br><br>
  Presently, I am broadening my skill set to encompass areas such as time series analysis and machine learning methods tailored for examining trends in energy systems. I am eager to continue my learning new ways to extract actionable insights from data within fast-paced and collaborative environments. 
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
