title: Shruti Misra # your name (or website title) here
logo: "/images/prof_pic2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a PhD student at the University of Washington with 5+ years of experience with interdisciplinary research and data science. My research leverages mixed method (quantitative and qualitative) approaches to study innovation ecosystems in digital health and clean technologies. 
  <br><br>
  My expertise lies in integrating statistical analysis and visualization of heterogenous data with stakeholder interviews and surveys to identify, define and refine actionable insights that help drive business and social impact.  
  <br><br>
  <a href="https://www.linkedin.com/in/shrutim14/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
